FROM python:latest 
RUN apt-get update && apt-get install -y \
    gpg-agent \
    wget \
RUN apt-get update && apt-get install -y 

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]
